### ISSUE TITLE
Firmware repo and rels links don't agree

### ISSUE THREAD

**Issue by adamsj182** [tigerclaw989/tinySA-ReleaseNotes#1]
The latest release on github shows it was released on Sept. 28. However, the repository link shows the latest release dated 2020-11-06 10:25 file name tinySA_v1.1-21-gc4d4935. When I used the old github rel. it reverted back to before a functioning waterfall was added. The firmware version from the git hub reads directly from the tinySA "version" tinySA_v1.1-17-gc13ee07.

The first picture should reflect the white waterfall after the firmware update:
![124071179_995418514269612_6082062189881815659_n](https://user-images.githubusercontent.com/50853374/98434626-bfc90800-208e-11eb-94a3-7d6b4a8d97e0.jpg)

The second picture should reflect the firmware version after building from source at the github repo:
![123874479_683065565675294_484305038061075529_n](https://user-images.githubusercontent.com/50853374/98434613-960fe100-208e-11eb-9f2c-e4aef9914898.jpg)

**Comment by tigerclaw989** [comment]
The developer doesn’t use GitHub for releases and the source on GitHub is likely outdated.

**Comment by adamsj182** [comment]
Yeah. I finally managed to get the correct firmware uploaded. It did not fix the white waterfall so I'll have to return and exchange the unit with the original vendor.
